extends Button

var tipy = [
	"\"Vytvořte si režim před spaním, který vašemu tělu naznačí, že je čas jít spát.\"",
	"\"Investujte do kvalitních lůžkovin a polštářů, abyste si zajistili pohodlné spaní.\"",
	"\"Během dne se vydejte na krátké procházky, abyste omezili sedavé zaměstnání.\"",
	"\"Praktikujte vděčnost tím, že budete vyjadřovat uznání lidem ve svém životě.\"",
	"\"Najděte způsob, jak do svého dne zařadit více smíchu, který má mnoho zdravotních výhod.\"",
	"\"Stanovte si konkrétní, měřitelné cíle, abyste mohli sledovat svůj pokrok.\"",
	"\"Omezte příjem cukru, abyste snížili riziko zdravotních problémů, jako je cukrovka a obezita.\"",
	"\"Praktikujte odpuštění, abyste se zbavili zášti a podpořili emocionální uzdravení.\"",
	"\"Najděte si čas na pravidelné sociální kontakty, abyste posílili pocit sounáležitosti.\"",
	"\"Cvičte všímavost tím, že se soustředíte na přítomný okamžik bez posuzování.\"",
	"\"Upřednostňujte činnosti péče o sebe, jako je např.\"",
	"\"Nastavte si realistická očekávání vůči sobě i ostatním, abyste snížili stres a frustraci.\"",
	"\"Stanovte si priority úkolů podle důležitosti a termínu, abyste zvýšili produktivitu.\"",
	"\"Věnujte se činnostem, které podporují relaxaci, například teplé koupeli nebo meditaci.\"",
	"\"Stanovte si důsledný spánkový režim, abyste zlepšili kvalitu a délku svého spánku.\"",
	"\"Najděte si zdravé způsoby, jak se vyrovnat se stresem, například cvičení, psaní deníku nebo rozhovor s přítelem.\"",
	"\"Stanovte si hranice ve vztahu k technologiím, aby nenarušovaly vaše vztahy nebo každodenní aktivity.\"",
	"\"Cvičte hluboká dechová cvičení, abyste snížili napětí a podpořili relaxaci.\"",
	"\"Upřednostňujte péči o sebe tím, že si uděláte čas na činnosti, které vás nabíjejí a omlazují.\"",
	"\"Věnujte se činnostem, které vám přinášejí radost a naplnění, ať už je to zahradničení, vaření nebo poslech hudby.\"",
	"\"Stanovte si realistické cíle, které jsou v souladu s vašimi hodnotami a prioritami.\"",
	"\"Vyjádřete vděčnost druhým tím, že jim poděkujete za jejich laskavost nebo podporu.\"",
	"\"Stanovte si zdravé hranice ve vztahu k práci, abyste předešli vyhoření a udrželi si zdravou rovnováhu mezi pracovním a soukromým životem.\"",
	"\"Cvičte se v soucitu se sebou tím, že se k sobě budete chovat laskavě a s porozuměním.\"",
	"\"Pravidelně se věnujte fyzické aktivitě, abyste si zlepšili náladu, snížili stres a zlepšili celkový zdravotní stav.\"",
	"\"Všímejte si svých myšlenek a pocitů, aniž byste je odsuzovali.\"",
	"\"Každý den si vyhraďte čas na relaxaci a aktivity na uvolnění stresu.\"",
	"\"Vyjádřete vděčnost za maličkosti v životě, jako je krásný západ slunce nebo milé gesto od cizího člověka.\"",
	"\"Upřednostňujte činnosti, které vám přinášejí radost a naplnění, i když se zdají být malé nebo bezvýznamné.\"",
	"\"Stanovte si hranice s toxickými lidmi nebo situacemi, abyste ochránili svou duševní a emocionální pohodu.\"",
	"\"Věnujte se činnostem, které podporují relaxaci a zklidnění, jako je pobyt v přírodě nebo cvičení jógy.\"",
	"\"Praktikujte vděčnost tím, že si každý den napíšete tři věci, za které jste vděční.\"",
	"\"Vytvořte si stálý spánkový režim tím, že budete chodit spát a vstávat každý den ve stejnou dobu.\"",
	"\"Upřednostněte péči o sebe tím, že si uděláte čas na aktivity, které vyživují vaši mysl, tělo i duši.\"",
	"\"Všímejte si svých myšlenek, pocitů a tělesných vjemů.\"",
	"\"Stanovte si realistické cíle, které jsou konkrétní, měřitelné, dosažitelné, relevantní a časově omezené (SMART).\"",
	"\"Vyjádřete vděčnost druhým tím, že napíšete děkovný dopis nebo vyslovíte upřímný kompliment.\"",
	"\"Stanovte si zdravé hranice ve vztahu k technologiím, aby se nestaly zdrojem stresu nebo rozptýlení.\"",
	"\"Pravidelně se věnujte fyzické aktivitě, abyste si zlepšili náladu a zvýšili hladinu energie.\"",
	"\"Každý den si vyhraďte čas na činnosti, které vám přinášejí radost a naplnění, ať už je to četba, malování nebo hudba.\"",
	"\"Upřednostňujte péči o sebe tím, že budete dostatečně spát, jíst výživné potraviny a pravidelně cvičit.\"",
	"\"Praktikujte vděčnost tím, že si povedete deník vděčnosti a každý den si zapíšete tři věci, za které jste vděční.\"",
	"\"Vytvořte si stálý spánkový režim tím, že budete chodit spát a vstávat každý den ve stejnou dobu, a to i o víkendech.\"",
	"\"Věnujte se činnostem, které podporují relaxaci a uvolnění stresu, například teplé koupeli nebo meditaci v duchu.\"",
	"\"Stanovte si realistické cíle, které jsou náročné, ale dosažitelné, a rozdělte je na menší úkoly, aby byly lépe zvládnutelné.\"",
	"\"Vyjádřete vděčnost druhým tím, že jim pošlete děkovný dopis, složíte jim poklonu nebo prostě řeknete 'děkuji'.\"",
	"\"Stanovte si zdravé hranice v práci tím, že si určíte limity pracovní zátěže, budete si v případě potřeby dělat přestávky a upřednostníte péči o sebe.\"",
	"\"Pravidelně se věnujte fyzické aktivitě, abyste si zlepšili náladu, snížili stres a posílili své celkové zdraví a pohodu.\"",
	"\"Cvičte všímavost tím, že budete věnovat pozornost přítomnému okamžiku a zbavíte se starostí o minulost nebo budoucnost.\"",
	"\"Každý den si vyhraďte čas na činnosti, které vám přinášejí radost a uspokojení, ať už jde o trávení času s blízkými, věnování se koníčkům nebo prostě jen relaxaci.\"",
	"\"Upřednostňujte péči o sebe tím, že si najdete čas na činnosti, které vyživují vaše tělo, mysl a duši, jako je dostatek spánku, výživná strava a pravidelné cvičení.\"",
	"\"Vytvořte si důsledný spánkový režim tím, že budete chodit do postele.\"",
	"\"Pamatuj, že pavouci se bojí víc tebe než ty jich.\"",
	"\"Usmívejte se a svět se bude usmívat s vámi. Mrač se a jsi na to sám.\"",
	"\"Nejezte sníh, který nemá barvu sněhu.\"",
	"\"Auta jsou špatná investice.\"",
	"\"Když máš šanci, využij ji!",
	"\"Nikdy si nestříhej třásně.\"",
	"\"Rozhodni se a neohlížej se zpět.\"",
	"\"Štěstí je cesta, ne cíl.\"",
	"\"Skutečné štěstí vždy spočívá v hledání.\"",
	"\"Nikdy neplaťte plnou cenu za pohovku v DFS.\"",
	"\"Vyvarujte se míchání zázvorových oříšků s jinými sušenkami, kontaminují. Držte je odděleně.\"",
	"\"Vždy blokujte trolly.\"",
	"\"Pokud se cítíte unavení nebo úzkostní, půllitr vody vám téměř vždy zlepší náladu.\"",
	"\"Život je lepší, když se zpívá o banánech.\"",
	"\"Když to není rozbité, neopravuj to.\"",
	"\"Být pověrčivý přináší smůlu.\"",
	"\"Někdy je nejlepší ignorovat rady ostatních.\"",
	"\"Nesuď knihu podle obalu, pokud nemá na zadní straně synopsi.\"",
	"\"Pokud se vám nedaří odšroubovat víčko sklenice, zkuste po jejím obvodu umístit gumičku, abyste ji lépe uchopili.\"",
	"\"Neodkládejte rozchod s někým, když víte, že ho chcete. Prodlužování situace ji jen zhoršuje.\"",
	"\"Nekrmte Mogwais po půlnoci.\"",
	"\"Tvůj úsměv může někomu zlepšit den, nezapomeň ho nosit.\"",
	"\"Když se plní splachovadlo, sedátko je pravděpodobně ještě teplé.\"",
	"\"Nikdy nekupujte levnou lepicí fólii.\"",
	"\"Nepřekračujte potoky.\"",
	"\"Při venčení psa v parku nenos čisté kalhoty.\"",
	"\"Když se díváš na ptáky letící nad hlavou, měj zavřená ústa.\"",
	"\"Až budeš starší, nauč se nikdy nevěřit prdu.\"",
	"\"Když máš pochybnosti, udělej další malý krok.\"",
	"\"Nikdy nenechávej svou matku, aby ti ostříhala vlasy.\"",
	"\"Všeho s mírou, včetně míry samotné.\"",
	"\"Nenech se semlít bastardy.\"",
	"\"Chcete-li zvýšit produktivitu, mějte vždy nějaký blbější úkol, který můžete odložit.\"",
	"\"Jen ten, kdo se pokouší o nemožné, může dosáhnout absurdního.\"",
	"\"Jestli si myslíš, že nikoho nezajímá, jestli jsi naživu, zkus vynechat pár plateb.\"",
	"\"Není vůbec žádný důvod se domnívat, že bílé víno se liší od vody, pokud jde o odstraňování skvrn od červeného vína.\"",
	"\"Nejchutnější koktejly mají často nejvyšší obsah alkoholu. Vždy se držte zpátky, abyste si zachovali důstojnost.\"",
	"\"Nikdy neběhejte maraton v Crocsech.\"",
	"\"Nikdy neběhejte s nůžkami.\"",
	"\"Nepoužívejte dokumenty Excel nebo Powerpoint pro základní potřeby zpracování textu.\"",
	"\"Vždy dvakrát zkontrolujte, zda jste soubor k e-mailu skutečně připojili.\"",
	"\"Snažte se každý den složit alespoň jednomu člověku kompliment.\"",
	"\"Pokud se cítíte sklesle, zkuste si na pět minut podržet tužku mezi horním rtem a nosem.\"",
	"\"Postavte si něco z LEGA, zlepší vám to den.\"",
	"\"Na důležitou schůzku jděte dobře oblečení.\"",
	"\"Pokud potřebujete povzbudit, zkuste si na internetu vyhledat fotky koťat.\"",
	"\"Dlouhá procházka o samotě s časem na přemýšlení může udělat zázraky.\"",
	"\"Chůze je naprosto správné řešení problémů s dopravními zácpami.\"",
	"\"Je špatné mít pravdu.\"",
	"\"Neslibuj, co nemůžeš splnit.\"",
	"\"Zdůrazňujte pozitiva, eliminujte negativa.\"",
	"\"Čím více nápadů rozdáte, tím více nápadů přijde k vám.\"",
	"\"Nehledejte pochvalu, hledejte kritiku.\"",
	"\"Snažte se dělat věci, kterých nejste schopni.\"",
	"\"Pokud se zaseknete, zkuste udělat opak toho, co řešení vyžaduje.\"",
	"\"Nepřednášejte projev. Předveďte se.\"",
	"\"Nebojte se hloupých nápadů.\"",
	"\"Neúspěch. Neuspějte znovu. Neuspěj lépe.\"",
	"\"Jednou za čas si dejte nějakou sladkost, kterou jste měli rádi, když jste byli mladší.\"",
	"\"Obejmout někoho může být oboustranně obohacující. Snažte se denně někoho alespoň jednou obejmout.\"",
	"\"Pokud se mačkáte v blízkosti cizích lidí ve veřejné dopravě, snažte se na ně nebýt hrubý. Takové situace nemá nikdo rád.\"",
	"\"Nemusíte si čistit všechny zuby nití. Jen ty, které si chcete nechat.\"",
	"\"Při vyklízení si položte otázku, zda má daná věc nějakou finanční, praktickou nebo sentimentální hodnotu. Pokud ne, vyhoďte ji.\"",
	"\"Jednou za čas si udělejte čas a alespoň na pět minut se podívejte na hvězdy, abyste pochopili svůj vesmírný význam.\"",
	"\"Počet upírů v průměrné domácnosti je přímo úměrný množství česnekového chleba v lednici.\"",
	"\"Návštěvníci jsou jako ryby: Ačkoli je můžete mít rádi, po třech dnech vám začnou smrdět.\"",
	"\"Nepokoušejte se nastartovat motorku na zledovatělé silnici.\"",
	"\"Je snadné si sednout a zpozornět, těžší je vstát a začít jednat.\"",
	"\"Nejezte nic, co by vaši prarodiče nepoznali jako jídlo.\"",
	"\"Jezte jídlo. Ne moc, hlavně rostliny.\"",
	"\"Práce není nikdy tak důležitá, jak si myslíte.\"",
	"\"Vždycky budeš litovat rundy tequily.\"",
	"\"Vždycky budeš litovat rundy JĂ¤germeistera.\"",
	"\"Milosrdenství je lepší část spravedlnosti.\"",
	"\"Být laskavý se vyplatí víc než mít pravdu.\"",
	"\"To, že tě někdo urazí, ještě neznamená, že máš pravdu.\"",
	"\"Názory jsou jako prdele, každý má nějaký.\"",
	"\"Na věku nezáleží, pokud nejste sýr.\"",
	"\"Na každý složitý problém existuje jasná, jednoduchá a špatná odpověď.\"",
	"\"K pytlíku s listím si dejte kousek kuchyňského rohlíku, aby vám déle vydrželo.\"",
	"\"Nikdy si nenastavujte budík, pokud nevíte, jak ho vypnout.\"",
	"\"Pokud nechceš, aby něco bylo veřejné, nezveřejňuj to na internetu.\"",
	"\"Nikdy nepište do e-mailu někomu něco, co byste mu neřekli do očí.\"",
	"\"Při praní obraťte džíny naruby, abyste zachovali jejich barvu.\"",
	"\"Podržte dveře pro další osobu.\"",
	"\"Nebojte se klást otázky.\"",
	"\"Vyčistěte si zuby hned, jak vstanete.\"",
	"\"Před jídlem vypijte sklenici vody.\"",
	"\"Dobré věci může být příliš mnoho.\"",
	"\"Čím výše jste ve firmě, tím je pravděpodobnější, že váš šéf je psychopat.\"",
	"\"Někdy se stačí omluvit. I když to není vaše vina.\"",
	"\"Dobrá rada je něco, co člověk dává, když je příliš starý na to, aby šel špatným příkladem.\"",
	"\"Nedávej druhým rady, kterými by ses sám neřídil.\"",
	"\"Pokud jste někdy na pochybách, zda si máte umýt vlasy, nebo ne: Umyj si je.\"",
	"\"Vždycky jsou to ti tišší.\"",
	"\"Uč se ze svých chyb.\"",
	"\"Každý dělá chyby.\"",
	"\"Pro lásku vždycky udělej cokoli, ale tohle nedělej.\"",
	"\"Říkej to tak, jak to je.\"",
	"\"Respektuj starší.\"",
	"\"Dělej, nebo nedělej. Není žádný pokus.\"",
	"\"Když se rozhlédneš a nevidíš nikoho, koho si vážíš, je čas odejít.\"",
	"\"Sdílený problém je poloviční problém.\"",
	"\"Když se nezeptáš, nedostaneš.\"",
	"\"Jednou z pěti nejčastějších výčitek lidí je, že nezůstali v kontaktu s přáteli.\"",
	"\"Nikdy nepojmenovávejte soubory nebo složky pomocí slova Konečná.\"",
	"\"Chcete-li čistě vyjmout semínko z avokáda, položte na něj pevně nůž a otočte jím.\"",
	"\"Přenechte své místo někomu, kdo ho potřebuje.\"",
	"\"Nejsi tak tlustý, jak si myslíš.\"",
	"\"Nejde o to, kdo tě má rád, ale o to, koho máš rád ty.\"",
	"\"Citron a sůl dělají zázraky na zašlou mosaz.\"",
	"\"Krok 1. Dávej si záležet. Krok 2. Nebuď hajzl. Krok 3. Vědět, kdy to nechat být.\"",
	"\"Jednou z pěti nejčastějších výčitek lidí je, že neměli odvahu být sami sebou.\"",
	"\"Častou výčitkou v životě je přání, aby měl člověk odvahu být sám sebou.\"",
	"\"Nepředpokládejte, že je něco možné nebo nemožné, dokud se nezeptáte lidí, kteří budou danou práci vykonávat.\"",
	"\"Přikývnutí je pro slepého koně stejně dobré jako mrknutí.\"",
	"\"Pokud si myslíte, že vám umírají sluchátka, zkontrolujte zásuvku, jestli není načechraná narovnanou sponkou.\"",
	"\"Polovinu života strávíte spánkem nebo v posteli. Vyplatí se utratit peníze za dobrou matraci, pořádné polštáře a pohodlnou peřinu.\"",
	"\"Zima se blíží.\"",
	"\"Častou výčitkou v životě je přání, aby člověk tolik nepracoval.\"",
	"\"Nekontrolujte pracovní e-mail ve dnech volna.\"",
	"\"Proč čekat s romantickým gestem až na Valentýna?",
	"\"Focení pomocí tabletů vypadá divně.\"",
	"\"Při objímání objímejte oběma rukama a vyvíjejte přiměřený, láskyplný tlak.\"",
	"\"Když jste na koncertě nebo akci, užívejte si ten okamžik, užívejte si, že tam jste. Zkuste nechat fotoaparát v kapse.\"",
	"\"Přestaňte prokrastinovat.\"",
	"\"Pokud máte prarodiče nebo rodiče - více s nimi mluvte. Ptej se jich na jejich životní zkušenosti.\"",
	"\"YOLO",
	"\"Opakujte jména lidí, když je potkáte.\"",
	"\"Pokud se přistihnete, že vás něco trápí, zeptejte se sami sebe, jestli na tom bude záležet i zítra, za týden nebo za měsíc.\"",
	"\"Člověk, který nikdy neudělal chybu, nikdy nic neudělal.\"",
	"\"Chceš-li být šťastně ženatý, vezmi si šťastného člověka.\"",
	"\"Na všem záleží, ale na ničem nezáleží tolik.\"",
	"\"Nejsi tak důležitý, důležité je to, co děláš.\"",
	"\"Udržujte to jednoduché.\"",
	"\"Když plešatíš, nečesej si vlasy přes pleš.\"",
	"\"Pokud vám řídnou vlasy, zkuste si je obarvit na podobný tón, jaký má vaše pokožka hlavy.\"",
	"\"Pokud s tím nemůžete nic dělat, nemá smysl se tím trápit.\"",
	"\"Při malování místnosti je klíčová příprava. Samotné malování by mělo tvořit asi 40 % práce.\"",
	"\"Pedantství je v pořádku, pokud nejste na straně příjemce. A ne pedant.\"",
	"\"Vždycky je to burrito.\"",
	"\"Dnes nepoužívejte slova tak trochu, tak nějak nebo možná. Buď to tak je, nebo to tak není.\"",
	"\"Neberte život příliš vážně.\"",
	"\"Někteří lidé by udělali lépe, kdyby se řídili svými vlastními radami.\"",
	"\"Jak se věci přibližují ke světlu, stíny jsou temnější.\"",
	"\"Nejdůležitější věc je ta, na kterou se nejsnáze zapomene.\"",
	"\"Když máš na výběr, udělej obojí.\"",
	"\"Přijímej rady.\"",
	"\"Zkus použít starý nápad.\"",
	"\"Vyjádřete problém slovy co nejjasněji.\"",
	"\"Co byste mohli zvýšit? Co byste mohli snížit?",
	"\"Život je dost krátký, nezávoďte do cíle.\"",
	"\"Když se vám v životě něco nepovede, prostě zakřičte dějový zvrat! a pokračujte dál.\"",
	"\"Život může být mnohem zajímavější ve vaší hlavě.\"",
	"\"Co ti brání?",
	"\"Pokud se ti nelíbí názor, který ti byl dán, sežeň si jiný.\"",
	"\"Občas si užijte trochu nesmyslů.\"",
	"\"Máš tolik hodin denně jako lidé, které nejvíce obdivuješ.\"",
	"\"Přestaňte používat termín zaneprázdněný jako výmluvu.\"",
	"\"Velké věci mají malé začátky.\"",
	"\"Některé z nejlepších životních lekcí dostáváme v těch nejhorších chvílích.\"",
	"\"Odstraňte zbytečnosti.\"",
	"\"Čím tišší jste, tím více slyšíte.\"",
	"\"Nikdo nezná nikoho jiného tak jako ty.\"",
	"\"Dělej trochu víc pro své přátele.\"",
	"\"Udělej něco nesobeckého.\"",
	"\"Lechtavý kašel léčíme nápojem z medu, citronu a co nejteplejší vody.\"",
	"\"Nemáš-li co hezkého říct, neříkej nic.\"",
	"\"Pokud vás to po týdnu stále svědí, jděte k lékaři.\"",
	"\"Vždy sázejte na černou.\"",
	"\"Buď dobrý milenec.\"",
	"\"Zasaď strom.\"",
	"\"Dobré věci přicházejí k těm, kteří čekají.\"",
	"\"Každý má své dny, kdy se mu nedaří. Nevybíjej si je na nevinných kolemjdoucích.\"",
	"\"Vždycky se to zdá nemožné, dokud to není hotové.\"",
	"\"Nikdy nelituj. Když je to dobré, je to báječné. Pokud je to špatné, je to zkušenost.\"",
	"\"Pravidlo číslo 1: Snaž se neumřít. Pravidlo číslo 2: Nebuď hajzl.\"",
	"\"Většina věcí vypadá lépe, když je dáš do kruhu.\"",
	"\"Vždycky si dejte dva cidery.\"",
	"\"V čem nechceš, v tom můžeš selhat. Takže můžeš rovnou riskovat, když budeš dělat to, co tě baví.\"",
	"\"Můžeš selhat v tom, co nechceš. Takže můžeš klidně zkusit dělat to, co tě baví.\"",
	"\"Jedna z nejlepších věcí na dospělosti je, že si můžeš koupit tolik LEGA, kolik chceš.\"",
	"\"Slunce vždycky svítí nad mraky.\"",
	"\"Dvakrát měř, jednou řež.\"",
	"\"Nesrovnávej se s ostatními.\"",
	"\"Nevěř vždy tomu, co si myslíš.\"",
	"\"Nauč se zvládat kritiku.\"",
	"\"Neber si to osobně.\"",
	"\"Važ si lidí ve svém životě.\"",
	"\"Nespoléhej se vždy na své pohodlí.\"",
	"\"Cvičení v dešti vám může dát pocit, že opravdu žijete.\"",
	"\"Mějte pevný stisk ruky.\"",
	"\"Dívejte se lidem do očí.\"",
	"\"Zpívejte si ve sprše.\"",
	"\"Buďte stateční. I když nejste, předstírejte, že jste. Nikdo to nepozná.\"",
	"\"Sarkasmus je nejnižší forma vtipu. Používejte ho správně a s výstižným načasováním.\"",
	"\"Nepálit mosty.\"",
	"\"Nikdy nepromarněte příležitost říct někomu, že ho máte rádi.\"",
	"\"Nejlepší sex je zábava.\"",
	"\"Nejlepší večery jsou, když se lidé kolem vás prostě baví.\"",
	"\"Snažte se nechválit lidi za věci, které neovládají.\"",
	"\"Neplýtvejte jídlem.\"",
	"\"Při rozhodování si vždy vyžádejte radu nebo názor.\"",
	"\"Hra je pravou matkou vynalézavosti.\"",
	"\"Většinu věcí, které se dělají tajně, je lepší nechat nedokončené.\"",
	"\"Nikdy doopravdy nedospěješ.\"",
	"\"Nejtěžší věci, které se říkají, jsou obvykle ty nejdůležitější.\"",
	"\"Kvalita je lepší než kvantita.\"",
	"\"Věci jsou jen věci. Nepřipoutávejte se k nim příliš.\"",
	"\"Jakmile najdeš opravdu dobrého přítele, nedělej nic, co by mohlo vaše přátelství pokazit.\"",
	"\"Zkus si udělat seznam.\"",
	"\"Určete si zdroje štěstí.\"",
	"\"Říká se, že tajemstvím štěstí je vděčnost.\"",
	"\"Pamatujte na jaký typ paliva jezdí vaše auto.\"",
	"\"Většina věcí není tak špatná, jak si myslíte.\"",
	"\"Sdílejte pozitivní energii.\"",
	"\"Respektujte názory ostatních lidí, i když se liší od vašich.\"",
	"\"Ocet je silný čisticí prostředek.\"",
	"\"Nepijte bělidlo.\"",
	"\"Věř, že to vyřešíš.\"",
	"\"Minulost nerovná se budoucnost.\"",
	"\"Neúspěch je jen další způsob, jak se naučit dělat něco správně.\"",
	"\"Jsi hoden a zasloužíš si úctu.\"",
	"\"Kdyby bylo všechno snadné, nudil by ses.\"",
	"\"Nezapomeňte si užívat cestu.\"",
	"\"Dávám si svolení dělat to, co je pro mě správné.\"",
	"\"Ostatní věří v tebe, věř ty v ně.\"",
	"\"Víš víc, než jsi věděl včera.\"",
	"\"Nezapomeň si užít cestu.\"",
	"\"Nedělej si starosti, pokud najdeš chyby ve svých minulých výtvorech, je to proto, že ses vyvinul.\"",
	"\"Není to chyba, je to příležitost k učení.\"",
	"\"Váš život je již zázrakem náhody, který čeká na to, až budete utvářet jeho osud.\"",
	"\"V nouzi poznaš přítele.\"",
	"\"Ve světe pro-gamingu je jen jedno pravidlo...\"",
	"\"Pravidla neurčují lidi, ale lidi určují pravidla\"",
	"\"Přidejte si citrón do čaje, bude tak zdravější\"",
	"\"Není nad oběd od babičky.\""
]

var text_label
var rng = RandomNumberGenerator.new()



# Called when the node enters the scene tree for the first time.
func _ready():
	text_label = $"../../../text"


# On"\"tip_dne" button click, show tip
func _on_pressed():
	text_label.text = tipy[rng.randi_range(0, len(tipy)-1)]
	Logger.write_to_log(name, "show tip", text_label.text)
	Logger.write_to_console(name, "show tip", text_label.text)

# Whole script has 300 LOC
